site_name: niina 的笔记本
site_url: https://niina.fun/notes
site_description: niina 的日记本
repo_name: niina/notes
repo_url: https://github.com/irorange27/notes
copyright: Copyright &copy; 2025 - Present <a href="https://github.com/irorange27/" target="_blank" rel="noopener">niina</a>

theme: 
  name: material
  language: en
  custom_dir: overrides